# Generated by Django 4.2.24 on 2025-10-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_course_user_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
