# Generated by Django 4.2.24 on 2025-10-20 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_semester'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
