# Generated by Django 4.2.24 on 2025-10-20 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0001_initial'),
        ('authentication', '0004_remove_semester_course_delete_course_delete_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_data.course'),
        ),
        migrations.AlterField(
            model_name='user',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_data.semester'),
        ),
    ]
