# Generated by Django 4.2.24 on 2025-10-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_course_alter_user_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('cr', 'Class Representative'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
