# Generated by Django 4.2.24 on 2025-10-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('cr', 'Class Representative'), ('staff', 'Staff')], default='student', max_length=20),
        ),
    ]
