# Generated by Django 4.2.24 on 2025-09-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrathanaLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Prathana location', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude of the location', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude of the location', max_digits=9)),
                ('start_time', models.TimeField(help_text='Start time for Prathana')),
                ('end_time', models.TimeField(help_text='End time for Prathana')),
            ],
        ),
    ]
