# Generated by Django 4.2.24 on 2025-09-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prathanalocation',
            name='latitude',
            field=models.DecimalField(decimal_places=15, help_text='Latitude of the location', max_digits=20),
        ),
        migrations.AlterField(
            model_name='prathanalocation',
            name='longitude',
            field=models.DecimalField(decimal_places=15, help_text='Longitude of the location', max_digits=20),
        ),
    ]
