# Generated by Django 4.2.24 on 2025-09-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_attendance', '0004_alter_prathanalocation_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prathanalocation',
            name='latitude',
            field=models.CharField(help_text='Latitude of the location', max_length=20),
        ),
        migrations.AlterField(
            model_name='prathanalocation',
            name='longitude',
            field=models.CharField(help_text='Longitude of the location', max_length=20),
        ),
    ]
