# Generated by Django 4.2.24 on 2025-09-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('take_attendance', '0005_alter_prathanalocation_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prathanalocation',
            name='radius',
            field=models.FloatField(default=100.0, help_text='Maximum allowed distance in meters'),
        ),
    ]
